#!/bin/sh
#
# myapp - this script starts and stops the myappserver daemon
#
# chkconfig:    - 85 15 
# description:  myapp is my app
# processname:  service.sh

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

prog="myapp"
myapp_service="/usr/share/myapp/myapp.sh"


lockfile=/var/lock/subsys/myapp

start() {
    [ -x $myapp_service ] || exit 5
    echo -n $"Starting $prog: "
    daemon $myapp_service
    retval=$?
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    kill `pgrep -f 'python.*8000'`
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

status() {
    if [ -f $lockfile ]; then
      echo myapp is running
      exit 0
    else
      echo myapp is stopped
      exit 3
    fi
}

case "$1" in
    start)
        [[ -f $lockfile ]] && exit 0
        $1
        ;;
    stop)
        [[ -f $lockfile ]] || exit 0
        $1
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac

